import { Alert, Button, Drawer, Form, Input, Select, Space, Switch, Tag } from 'antd';

const generationModeOptions = [
  { label: 'Default', value: 'default' },
  { label: 'Custom Prefix', value: 'customPrefix' },
];

export type ReferenceConfigTarget = {
  direction: 'outbound' | 'inbound';
  placement: 'init-order';
};

type Props = {
  open: boolean;
  target: ReferenceConfigTarget;
  initialValues?: Record<string, unknown>;
  readOnly?: boolean;
  onClose: () => void;
  onSave: (config: Record<string, unknown>) => void;
};

export default function ReferenceGenerationDrawer({ open, target, initialValues = {}, readOnly = false, onClose, onSave }: Props) {
  const [form] = Form.useForm();
  const generationEnabled = Form.useWatch('referenceGenerationEnabled', form);
  const generationMode = Form.useWatch('referenceGenerationMode', form);
  const isOutbound = target.direction === 'outbound';
  const referenceType = isOutbound ? 'Request' : 'Response';
  const componentCode = isOutbound ? 'initOutboundOrder' : 'initInboundOrder';
  const componentName = `Initialize ${isOutbound ? 'Outbound' : 'Inbound'} Order`;
  const priorityItems = isOutbound
    ? [
        'Request Reference passed in by the upstream system',
        'Request Reference generated by initOutboundOrder',
      ]
    : [
        'Response Reference generated by initInboundOrder',
      ];
  const showGenerationFields = generationEnabled;

  return (
    <Drawer
      title={<Space><span>Configure {componentName}</span><Tag color="blue">{componentCode}</Tag></Space>}
      width={560}
      open={open}
      onClose={onClose}
      destroyOnClose
      extra={!readOnly && <Space><Button onClick={onClose}>Cancel</Button><Button type="primary" onClick={() => form.validateFields().then(onSave)}>Save</Button></Space>}
    >
      <Form
        form={form}
        layout="vertical"
        disabled={readOnly}
        initialValues={{ referenceGenerationEnabled: false, ...initialValues }}
      >
        <Form.Item
          name="referenceGenerationEnabled"
          label={`Generate ${referenceType} Reference`}
          valuePropName="checked"
        >
          <Switch />
        </Form.Item>

        {showGenerationFields && <>
          <Alert
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
            message={`${referenceType} Reference priority`}
            description={<>
              <ol style={{ margin: '6px 0 6px', paddingLeft: 20 }}>
                {priorityItems.map((item) => <li key={item}>{item}</li>)}
              </ol>
              <div>The highest-priority available value is always used.</div>
            </>}
          />

          <Form.Item
            name="referenceGenerationMode"
            label="Reference Generation Mode"
            rules={[{ required: true, message: 'Select a Reference Generation Mode' }]}
          >
            <Select placeholder="Select generation mode" options={generationModeOptions} />
          </Form.Item>

          {generationMode === 'customPrefix' && <Form.Item
            name="referencePrefix"
            label="Prefix"
            rules={[{ required: true, whitespace: true, message: 'Enter a Prefix' }]}
          >
            <Input placeholder="Enter reference prefix" />
          </Form.Item>}
        </>}
      </Form>
    </Drawer>
  );
}
