import { Alert, Button, Drawer, Form, Input, Select, Space, Switch, Tag } from 'antd';

const generationModeOptions = [
  { label: 'Default', value: 'default' },
  { label: 'Orig Order Request Reference', value: 'origOrderRequestReference' },
  { label: 'Orig Order Response Reference', value: 'origOrderResponseReference' },
  { label: 'Prefix', value: 'prefix' },
];

export type ReferenceConfigTarget = {
  direction: 'outbound' | 'inbound';
  placement: 'init-order' | 'standalone';
};

type Props = {
  open: boolean;
  target: ReferenceConfigTarget;
  initialValues?: Record<string, unknown>;
  readOnly?: boolean;
  onClose: () => void;
  onSave: (config: Record<string, unknown>) => void;
};

export default function ReferenceGenerationDrawer({ open, target, initialValues = {}, readOnly = false, onClose, onSave }: Props) {
  const [form] = Form.useForm();
  const generationEnabled = Form.useWatch('referenceGenerationEnabled', form);
  const generationMode = Form.useWatch('referenceGenerationMode', form);
  const isOutbound = target.direction === 'outbound';
  const isInitOrder = target.placement === 'init-order';
  const referenceType = isOutbound ? 'Request' : 'Response';
  const componentCode = isInitOrder
    ? (isOutbound ? 'initOutboundOrder' : 'initInboundOrder')
    : (isOutbound ? 'generateRequestReference' : 'generateResponseReference');
  const componentName = isInitOrder
    ? `Initialize ${isOutbound ? 'Outbound' : 'Inbound'} Order`
    : `Generate ${referenceType} Reference`;
  const priorityItems = isOutbound
    ? [
        'Request Reference passed in by the upstream system',
        'Request Reference generated by initOutboundOrder',
        'Request Reference generated by generateRequestReference',
      ]
    : [
        'Response Reference generated by initInboundOrder',
        'Response Reference generated by generateResponseReference',
      ];
  const showGenerationFields = !isInitOrder || generationEnabled;

  return (
    <Drawer
      title={<Space><span>Configure {componentName}</span><Tag color="blue">{componentCode}</Tag></Space>}
      width={560}
      open={open}
      onClose={onClose}
      destroyOnClose
      extra={!readOnly && <Space><Button onClick={onClose}>Cancel</Button><Button type="primary" onClick={() => form.validateFields().then(onSave)}>Save</Button></Space>}
    >
      <Form
        form={form}
        layout="vertical"
        disabled={readOnly}
        initialValues={isInitOrder ? { referenceGenerationEnabled: false, ...initialValues } : initialValues}
      >
        {isInitOrder && <Form.Item
          name="referenceGenerationEnabled"
          label={`Generate ${referenceType} Reference`}
          valuePropName="checked"
        >
          <Switch />
        </Form.Item>}

        {showGenerationFields && <>
          <Alert
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
            message={`${referenceType} Reference priority`}
            description={<>
              <ol style={{ margin: '6px 0 6px', paddingLeft: 20 }}>
                {priorityItems.map((item) => <li key={item}>{item}</li>)}
              </ol>
              <div>The highest-priority available value is always used.</div>
            </>}
          />

          {!isInitOrder && <Alert
            type="warning"
            showIcon
            style={{ marginBottom: 16 }}
            message="Order reference is not updated"
            description={`The ${referenceType.toLowerCase()} reference generated by this component is not written back to the order, even when the Flow has an order.`}
          />}

          <Form.Item
            name="referenceGenerationMode"
            label="Reference Generation Mode"
            rules={isInitOrder ? [{ required: true, message: 'Select a Reference Generation Mode' }] : undefined}
          >
            <Select allowClear={!isInitOrder} placeholder="Select generation mode" options={generationModeOptions} />
          </Form.Item>

          {generationMode === 'prefix' && <Form.Item
            name="referencePrefix"
            label="Prefix"
            rules={[{ required: true, whitespace: true, message: 'Enter a Prefix' }]}
          >
            <Input placeholder="Enter reference prefix" />
          </Form.Item>}
        </>}
      </Form>
    </Drawer>
  );
}
