// Channel types
export interface Channel {
  code: string;
  country: string[];
  party: string;
  status: 'Active' | 'Inactive';
}

export interface BusinessType {
  bt: string;
  mode: 'Config Integration' | 'Code Integration';
}

export interface Ability {
  bt: string;
  ability: string;
  publishStatus: 'draft' | 'pending' | 'published';
  badges: Array<{ cloud: string; env: string }>;
}

export interface MatchRule {
  id: string;
  field1: string;
  field2: string;
  bt: string;
  ability: string;
  action: string;
}

export interface InboundEndpoint {
  name: string;
  url: string;
  fields: string[];
  matchType: 'A' | 'B';
  singleNoField: string;
  matchFields: string[];
  rules: MatchRule[];
}

export interface StepConfig {
  name: string;
  triggerMode: 'upstream' | 'external';
  finalStateMode: ('requery' | 'callback' | 'sync')[];
  produceEvents: string[];
  triggerEvents: string[];
  triggerEventSources?: number[];
}

export interface FieldMapping {
  endpointField: string;
  mode: 'direct' | 'condition' | 'fixed';
  contextField?: string;
  fieldType: string;
  operation: string;
  conditions?: Array<{
    field: string;
    op: string;
    value: string;
    result: string;
  }>;
  defaultValue?: string;
  fixedValue?: string;
  multiplier?: number;
}

// Flow configuration types

export type ExecutionType = 'single' | 'loop';
export type FlowType = 'outbound' | 'inbound';
export type EndType = 'event' | 'state' | 'wait_upstream' | 'wait_external';
export type TriggerType = 'upstream' | 'external' | 'timer' | 'callback';

export interface EventCondition {
  id: string;
  field: string;
  operator: string;
  value: string;
  logic?: string;
  result?: string;
}

export interface FlowEvent {
  id: string;
  eventName: string;
  conditions: Array<{
    id: string;
    field: string;
    operator: string;
    value: string;
    logic: string;
  }>;
}

export interface OutputEvent {
  eventName: string;
  conditions?: EventCondition[];
}

export interface FlowConfig {
  id: string;
  name: string;
  executionType: ExecutionType;
  flowType: FlowType;
  endType: EndType;
  // Step index (1, 2, 3...) for positioning in canvas
  stepIndex?: number;
  // Trigger type for the flow
  triggerType?: TriggerType;
  // Trigger events (for flows that are triggered by events)
  triggerEvents?: string[];
  // Output events generated by this flow
  outputEvents?: OutputEvent[];
  // For event end type - list of events this flow can generate
  events?: FlowEvent[];
  // For state end type
  stateConditions?: EventCondition[];
  // Whether this flow is configured
  isConfigured?: boolean;
}

export interface StateFlowData {
  stateName: string;
  flows: FlowConfig[];
  // Available events from previous flows (for trigger configuration)
  availableEvents?: string[];
}