// Channel types
export interface Channel {
  code: string;
  country: string[];
  party: string[];
  status: 'Active' | 'Inactive';
  operator: string;
  operationTime: string;
}

export interface BusinessType {
  bt: string;
  mode: 'Config Integration' | 'Code Integration';
}

export interface Ability {
  bt: string;
  ability: string;
  publishStatus: 'draft' | 'pending' | 'published';
  badges: Array<{ cloud: string; env: string }>;
}

export interface MatchRule {
  id: string;
  fieldValues: Record<string, string>;
  bt: string;
  ability: string;
  action: string;
  requestType: 'CALLBACK' | 'EXTERNAL_INBOUND';
}

export type MatchingType = 'single' | 'order_no' | 'type_field' | 'custom';
export type UriConfigStatus = 'draft' | 'submitted' | 'deployed' | 'deprecated' | 'legacy_readonly' | 'error';

export interface InboundRequestField {
  id: string;
  source: 'query' | 'header' | 'body';
  name: string;
  type: 'String' | 'Number' | 'Boolean' | 'Object';
  moc: 'yes' | 'no';
  description: string;
}

export interface LegacyInboundComponent {
  id: string;
  code: string;
  name: string;
  config: Record<string, string | boolean>;
}

export interface CapabilityDecisionVersion {
  id: string;
  version: string;
  name: string;
  sourceType: 'legacy' | 'v2';
  configStatus: UriConfigStatus;
  fields: string[];
  requestFields: InboundRequestField[];
  matchType: MatchingType;
  matchFieldSource?: 'query' | 'header' | 'body';
  singleNoField: string;
  referenceField?: 'requestReference' | 'responseReference';
  matchFields: string[];
  rules: MatchRule[];
  customScript?: string;
  fallbackBehavior?: 'reject' | 'alert_and_reject' | 'manual_review';
  decryptEnabled?: boolean;
  badges?: Array<{ cloud: string; env: string }>;
  hasUnsubmittedDraft?: boolean;
  draftBaseline?: string;
  legacyComponents?: LegacyInboundComponent[];
  updatedTime?: string;
  operator?: string;
}

export interface InboundEndpoint {
  id: string;
  name: string;
  url: string;
  businessType: string;
  businessTypes: string[];
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  uriType: 'new' | 'legacy';
  description: string;
  fields: string[];
  matchType: MatchingType;
  matchFieldSource?: 'query' | 'header' | 'body';
  singleNoField: string;
  referenceField?: 'requestReference' | 'responseReference';
  matchFields: string[];
  rules: MatchRule[];
  customScript?: string;
  fallbackBehavior?: 'reject' | 'alert_and_reject' | 'manual_review';
  decryptEnabled?: boolean;
  version: string;
  configStatus: UriConfigStatus;
  badges?: Array<{ cloud: string; env: string }>;
  referenceCount?: number;
  updatedTime?: string;
  operator?: string;
  versions: CapabilityDecisionVersion[];
}

export interface StepConfig {
  name: string;
  triggerMode: 'upstream' | 'external';
  finalStateMode: ('requery' | 'callback' | 'sync')[];
  produceEvents: string[];
  triggerEvents: string[];
  triggerEventSources?: number[];
}

export interface FieldMapping {
  endpointField: string;
  mode: 'direct' | 'condition' | 'fixed';
  contextField?: string;
  fieldType: string;
  operation: string;
  conditions?: Array<{
    field: string;
    op: string;
    value: string;
    result: string;
  }>;
  defaultValue?: string;
  fixedValue?: string;
  multiplier?: number;
}

// Flow configuration types

export type ExecutionType = 'single' | 'loop';
export type FlowType = 'outbound' | 'inbound';
export type EndType = 'event' | 'state' | 'wait_upstream' | 'wait_external';
export type TriggerType = 'UPSTREAM_TRIGGERED' | 'EXTERNAL_INBOUND_TRIGGERED' | 'CALLBACK_TRIGGERED' | 'ASYNC_TRIGGERED' | 'SCHEDULED_TRIGGERED';

export interface EventCondition {
  id: string;
  field: string;
  operator: string;
  value: string;
  logic?: string;
  result?: string;
}

export interface FlowEvent {
  id: string;
  eventName: string;
  conditions: Array<{
    id: string;
    field: string;
    operator: string;
    value: string;
    logic: string;
  }>;
}

export interface OutputEvent {
  eventName: string;
  conditions?: EventCondition[];
}

export interface FlowCanvasNode {
  id: string;
  componentCode: string;
  x: number;
  y: number;
  status: 'not_started' | 'editing' | 'complete' | 'error' | 'need_review' | 'readonly';
}

export interface FlowCanvasEdge {
  id: string;
  source: string;
  target: string;
}

export interface FlowConfig {
  id: string;
  name: string;
  executionType: ExecutionType;
  flowType: FlowType;
  endType: EndType;
  // Step index (1, 2, 3...) for positioning in canvas
  stepIndex?: number;
  // Trigger type for the flow
  triggerType?: TriggerType;
  // Trigger events (for flows that are triggered by events)
  triggerEvents?: string[];
  // Action context borrowed by async or scheduled flows; it is not a direct trigger.
  contextActions?: string[];
  // Stable Match Capability URI ID used in the inbound Route Key.
  inboundUriId?: string;
  // Output events generated by this flow
  outputEvents?: OutputEvent[];
  // For event end type - list of events this flow can generate
  events?: FlowEvent[];
  // For state end type
  stateConditions?: EventCondition[];
  // Whether this flow is configured
  isConfigured?: boolean;
  // Canvas data lives with the Flow during the current demo session.
  canvasNodes?: FlowCanvasNode[];
  canvasEdges?: FlowCanvasEdge[];
}

export interface StateFlowData {
  stateName: string;
  flows: FlowConfig[];
  // Available events from previous flows (for trigger configuration)
  availableEvents?: string[];
}

// Cloud and environment types for publish status
export type CloudType = 'MFB' | 'BD' | 'PK' | 'ALIYUN' | 'ALIYUN_FRANKFURT' | 'ONELOOP';
export type EnvType = 'DAILY' | 'PRE' | 'PROD';

// Publish status for flow version
export type PublishStatusType = 'draft' | 'submitted' | 'deployed';

// Flow version (sub-record) under a BT + Ability
export interface FlowVersion {
  id: string;
  version: string;
  publishStatus: PublishStatusType;
  badges: Array<{ cloud: CloudType; env: EnvType }>;
  hasUnsubmittedDraft?: boolean;
  remark?: string;
  operator: string;
  operationTime: string;
  flows: FlowConfig[];
}

// Config Ability main record (BT + Ability)
export interface ConfigAbility {
  bt: string;
  ability: string;
  actions: string[];
  stateMachine: string;
  versions: FlowVersion[];
}
